#!/bin/bash
#
# This script starts and stops the ferret DRb server
# chkconfig: 2345 89 36
# description: Ferret search engine for ruby apps.
#
# save the current directory
CURDIR=`pwd`
PATH=/usr/local/bin:$PATH

RORPATH="/home/rails/istockcv/current"

case "$1" in
  start)
     cd $RORPATH
     echo "Starting ferret DRb server."
     su rails -c "script/ferret_server -e production start"
     ;;
  stop)
     cd $RORPATH
     echo "Stopping ferret DRb server."
     su rails -c "script/ferret_server -e production stop"
    ;;
  *)
     echo $"Usage: $0 {start, stop}"
     exit 1
     ;;
esac

cd $CURDIR